// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmS22lEvbvz9bA7NVnUT4EKAejGQdMgUM',
    appId: '1:277949983647:web:4a204e05887077e034abaa',
    messagingSenderId: '277949983647',
    projectId: 'bluber-340aa',
    authDomain: 'bluber-340aa.firebaseapp.com',
    storageBucket: 'bluber-340aa.appspot.com',
    measurementId: 'G-3GR9E459YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslgGggb4rzLCQrcMNj4BJGzh3TorRp74',
    appId: '1:277949983647:android:b8aadc59c5544cdc34abaa',
    messagingSenderId: '277949983647',
    projectId: 'bluber-340aa',
    storageBucket: 'bluber-340aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6uOFvg8LWrMzyYaZHdrWGFuBz3XsQTo',
    appId: '1:277949983647:ios:c869f7e6e961417434abaa',
    messagingSenderId: '277949983647',
    projectId: 'bluber-340aa',
    storageBucket: 'bluber-340aa.appspot.com',
    iosBundleId: 'com.example.bluber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6uOFvg8LWrMzyYaZHdrWGFuBz3XsQTo',
    appId: '1:277949983647:ios:fe8807ccc580e8c134abaa',
    messagingSenderId: '277949983647',
    projectId: 'bluber-340aa',
    storageBucket: 'bluber-340aa.appspot.com',
    iosBundleId: 'com.example.bluber.RunnerTests',
  );
}
